
services:
  database:
    image: mysql:${MYSQL_VERSION:-5.7}-alpine
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-*Bmanpj1*}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-*Bmanpj1*}
    volumes:
      - database_data:/var/lib/mysql
 


volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

